
const fs = require("fs");
const path = "g:/PROJECTS/FULL STACK PROJECTS/New-portfolio/src/lib/constants.ts";
let content = fs.readFileSync(path, "utf8");

const newProjects = `export const PROJECTS = [
  {
    id: 1,
    name: "Collexa",
    tagline: "Full Stack College Platform",
    description: "A comprehensive full-stack platform designed for college students — featuring resources, collaboration tools, event management, and academic utilities.",
    tech: ["React", "Node.js", "MongoDB", "Express", "TailwindCSS"],
    category: "Full Stack",
    github: "https://github.com/gagandeepkushwah",
    live: "#",
    featured: true,
    color: "#4f8ef7",
    image: "/Collexa.png",
  },
  {
    id: 2,
    name: "StockPilot",
    tagline: "Virtual Trading Simulator",
    description: "A virtual trading simulator where users are given virtual money to practice trading stocks, analyze markets, and learn investing without financial risk.",
    tech: ["Next.js", "TypeScript", "TailwindCSS", "Framer Motion"],
    category: "Full Stack",
    github: "https://github.com/gagandeepkushwah",
    live: "#",
    featured: true,
    color: "#34d399",
    image: "/dashboard.png",
  },
  {
    id: 3,
    name: "DormiQ",
    tagline: "Smart Student Housing Platform",
    description: "A student housing and hostel management platform that simplifies room booking, roommate matching, grievance filing, and digital operations.",
    tech: ["Next.js", "TypeScript", "TailwindCSS", "MongoDB"],
    category: "Full Stack",
    github: "https://github.com/gagandeepkushwah",
    live: "#",
    featured: true,
    color: "#a78bfa",
    image: "/dormiq.png",
  },
  {
    id: 4,
    name: "InterviewAI",
    tagline: "AI-Powered Mock Interviews",
    description: "An intelligent platform that conducts mock interviews using AI, analyzing facial expressions, tone, and answers to provide actionable feedback.",
    tech: ["React", "OpenAI API", "WebRTC", "TailwindCSS"],
    category: "AI / ML",
    github: "https://github.com/gagandeepkushwah",
    live: "#",
    featured: true,
    color: "#f472b6",
  },
  {
    id: 5,
    name: "NCA Score",
    tagline: "Comprehensive Scoring System",
    description: "A specialized scoring and analytics platform designed to evaluate and track performance metrics with interactive dashboards.",
    tech: ["React", "Node.js", "Chart.js", "PostgreSQL"],
    category: "Full Stack",
    github: "https://github.com/gagandeepkushwah",
    live: "#",
    featured: false,
    color: "#fbbf24",
  },
  {
    id: 6,
    name: "RKS Wealth Website",
    tagline: "Financial Services Portal",
    description: "A professional financial advisory website featuring robust calculators, client portals, and seamless API integrations for real-time data.",
    tech: ["Next.js", "React", "TailwindCSS", "Framer Motion"],
    category: "Web Dev",
    github: "https://github.com/gagandeepkushwah",
    live: "#",
    featured: false,
    color: "#38bdf8",
  },
  {
    id: 7,
    name: "Human Following Robot",
    tagline: "Autonomous Robotics",
    description: "An autonomous robot that detects and follows a human using ultrasonic sensors, IR sensors, and Arduino microcontroller.",
    tech: ["Arduino", "C", "Sensors", "Motors"],
    category: "Electronics",
    github: "https://github.com/gagandeepkushwah",
    live: "#",
    featured: false,
    color: "#22d3ee",
  },
  {
    id: 8,
    name: "Advanced Predictive Maintenance",
    tagline: "Aircraft Engine ML Model",
    description: "A machine learning solution for aircraft engines that analyzes sensor telemetry to predict remaining useful life and prevent catastrophic failures.",
    tech: ["Python", "TensorFlow", "Pandas", "Scikit-Learn"],
    category: "AI / ML",
    github: "https://github.com/gagandeepkushwah",
    live: "#",
    featured: true,
    color: "#ef4444",
  },
  {
    id: 9,
    name: "Tumor Detection using DL",
    tagline: "Medical Imaging Analysis",
    description: "A deep learning application utilizing Convolutional Neural Networks (CNNs) to accurately detect and segment tumors from MRI scans.",
    tech: ["Python", "PyTorch", "OpenCV", "Deep Learning"],
    category: "AI / ML",
    github: "https://github.com/gagandeepkushwah",
    live: "#",
    featured: true,
    color: "#8b5cf6",
  },
  {
    id: 10,
    name: "UAV Spoofing Security",
    tagline: "Drone Security Research",
    description: "Working on identifying vulnerabilities in UAV communication protocols and developing countermeasures against GPS and signal spoofing attacks.",
    tech: ["SDR", "Signal Processing", "Python", "Cybersecurity"],
    category: "Electronics",
    github: "https://github.com/gagandeepkushwah",
    live: "#",
    featured: true,
    color: "#10b981",
  },
  {
    id: 11,
    name: "Arduino Water Level Indicator",
    tagline: "IoT Embedded System",
    description: "An intelligent water level monitoring system using ultrasonic sensors and Arduino with alerts for tank overflow prevention.",
    tech: ["Arduino", "C", "Ultrasonic Sensor", "IoT"],
    category: "Electronics",
    github: "https://github.com/gagandeepkushwah",
    live: "#",
    featured: false,
    color: "#6366f1",
  },
  {
    id: 12,
    name: "Invisible Burglar Alarm",
    tagline: "Security Electronics System",
    description: "A cost-effective invisible burglar alarm using IR sensors and LDR creating an invisible beam.",
    tech: ["Electronics", "IR Sensors", "555 Timer"],
    category: "Electronics",
    github: "https://github.com/gagandeepkushwah",
    live: "#",
    featured: false,
    color: "#ec4899",
  }
];`

content = content.replace(/export const PROJECTS = \[[\s\S]*?\];/m, newProjects);
fs.writeFileSync(path, content);
console.log("Updated projects");

